# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:49:21+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query

from models import (
    Account,
    Call,
    CallCreate,
    CallTransfer,
    Direction,
    ErrorResponse,
    EventsCount,
    Order,
    SelfCallsGetResponse,
    SelfCallsIdDeleteResponse,
    SelfCallsIdGetResponse,
    SelfCallsPostResponse,
    SelfEventsGetResponse,
    SelfEventsIdGetResponse,
    SelfWebhooksGetResponse,
    States,
    States4,
    States6,
    Types,
    User,
    Webhook,
    WebhookCreate,
)

app = MCPProxy(
    contact={
        'email': 'gunifydevops@vonage.com',
        'name': 'VGIS',
        'url': 'https://integrate.vonage.com',
    },
    description='The Vonage Integration Suite API enables call control and webhooks for call events.\n\nYour application must subscribe to the VonageIntegrationSuite API suite to use this API.\n',
    title='Vonage Integration Suite',
    version='1.0.1',
    servers=[{'url': 'https://api.vonage.com/t/vbc.prod/vis/v1'}],
)


@app.get('/self', tags=['user_account_management'])
def get_user():
    """
    User info
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/account', tags=['user_account_management'])
def get_account():
    """
    Account info
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/self/calls',
    description=""" Lists currently active calls """,
    tags=['call_operation_management', 'event_tracking_management'],
)
def list_calls(
    from_date: Optional[int] = Query(None, alias='fromDate'),
    to_date: Optional[int] = Query(None, alias='toDate'),
    direction: Optional[Direction] = None,
    states: Optional[States] = 'ACTIVE',
    offset: Optional[int] = None,
    size: Optional[int] = 20,
    order: Optional[Order] = 'ASC',
    sort: Optional[str] = None,
):
    """
    List active calls
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/self/calls', tags=['call_operation_management'])
def create_call(body: CallCreate):
    """
    Place a call
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/calls/count', tags=['call_operation_management'])
def get_calls_count(
    from_date: Optional[int] = Query(None, alias='fromDate'),
    to_date: Optional[int] = Query(None, alias='toDate'),
    direction: Optional[Direction] = None,
    states: Optional[States] = 'ACTIVE',
):
    """
    Get calls count
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/self/calls/{id}', tags=['call_operation_management'])
def destroy_call(id: str):
    """
    End a call
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/calls/{id}', tags=['call_operation_management'])
def get_roles(id: str):
    """
    Get a call
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/self/calls/{id}/answer', tags=['call_operation_management'])
def call_answer(id: str):
    """
    Answer call (On supported devices)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/self/calls/{id}/hold', tags=['user_account_management'])
def call_unold(id: str):
    """
    Unhold
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/self/calls/{id}/hold', tags=['call_operation_management'])
def call_hold(id: str):
    """
    Put call on hold
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/self/calls/{id}/transfer', tags=['call_operation_management'])
def call_transfer(id: str, body: CallTransfer = ...):
    """
    Transfer call
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/self/calls/{id}/vmtransfer', tags=['call_operation_management'])
def call_v_m_transfer(id: str):
    """
    Send call to voicemail
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/events', tags=['event_tracking_management'])
def list_events(
    types: Optional[Types] = None,
    from_date: Optional[int] = Query(None, alias='fromDate'),
    to_date: Optional[int] = Query(None, alias='toDate'),
    direction: Optional[Direction] = None,
    states: Optional[States4] = None,
    offset: Optional[int] = None,
    size: Optional[int] = 20,
    order: Optional[Order] = 'ASC',
    sort: Optional[str] = None,
):
    """
    List events
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/events/count', tags=['event_tracking_management'])
def get_events_count(
    from_date: Optional[int] = Query(None, alias='fromDate'),
    to_date: Optional[int] = Query(None, alias='toDate'),
    direction: Optional[Direction] = None,
    states: Optional[States6] = None,
):
    """
    Get events count
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/events/{id}', tags=['event_tracking_management'])
def get_event(id: str):
    """
    Get event
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/webhooks', tags=['webhook_subscription_management'])
def list_webhooks():
    """
    List web hooks
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/self/webhooks', tags=['webhook_subscription_management'])
def create_webhook(body: WebhookCreate):
    """
    Create a new webhook subscription
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/self/webhooks/{id}', tags=['webhook_subscription_management'])
def destroy_webhook(id: str):
    """
    Remove a web hook
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/self/webhooks/{id}', tags=['webhook_subscription_management'])
def view_webhook(id: str):
    """
    Get web hook details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put('/self/webhooks/{id}/renew', tags=['webhook_subscription_management'])
def renew_webhook(id: str):
    """
    Renews a web hook
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
