# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:49:21+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Status(Enum):
    PENDING = 'PENDING'
    ACTIVE = 'ACTIVE'
    DELETED = 'DELETED'
    ARCHIVED = 'ARCHIVED'


class Health(BaseModel):
    message: Optional[str] = None
    status: Optional[str] = None


class Uci(BaseModel):
    health: Optional[Health] = None
    id: Optional[int] = None
    type: Optional[str] = 'ACCOUNT_UCI'
    ucpAccountId: Optional[str] = None
    ucpLabel: Optional[str] = None


class Account(BaseModel):
    id: Optional[int] = Field(
        None, description='Unique identifier of the account', examples=[257073]
    )
    name: Optional[str] = Field(
        None, description='Name of the account', examples=['Vonage']
    )
    org: Optional[str] = Field(
        None, description='Organization of the account', examples=['Vonage']
    )
    status: Optional[Status] = Field(
        None, description='Status of the account', examples=['ACTIVE']
    )
    ucis: Optional[List[Uci]] = None


class Direction(Enum):
    INBOUND = 'INBOUND'
    OUTBOUND = 'OUTBOUND'


class State(Enum):
    INITIALIZING = 'INITIALIZING'
    RINGING = 'RINGING'
    ACTIVE = 'ACTIVE'
    HELD = 'HELD'
    REMOTE_HELD = 'REMOTE_HELD'
    DETACHED = 'DETACHED'
    REJECTED = 'REJECTED'
    CANCELLED = 'CANCELLED'
    ANSWERED = 'ANSWERED'
    MISSED = 'MISSED'


class Type(Enum):
    CALL = 'CALL'


class Call(BaseModel):
    accountId: int = Field(..., description='Unique identifier of the account')
    answerTime: Optional[date] = Field(None, description='Time to answer the call')
    callerId: Optional[str] = Field(None, description='Remote caller ID')
    direction: Direction = Field(..., description='Direction of the call')
    duration: int = Field(..., description='Duration of the call in milliseconds')
    endTime: Optional[date] = Field(None, description='End time of the call')
    externalId: Optional[str] = Field(
        None, description='External identifier of the call'
    )
    id: int = Field(..., description='Unique identifier of the call')
    phoneNumber: str = Field(..., description='Unique identifier of the account')
    startTime: date = Field(..., description='Start time of the call')
    state: State = Field(..., description='Status of the call')
    type: Type = Field(..., description='Record type')
    uciId: int = Field(..., description='Unique identifier of communications provider')
    userId: int = Field(..., description='Unique identifier of the user')


class CallCreate(BaseModel):
    phoneNumber: str = Field(..., description='Phone number to call')


class CallTransfer(BaseModel):
    phoneNumber: str = Field(..., description='Phone number to transfer to')


class Error(BaseModel):
    field: Optional[str] = None
    message: Optional[str] = None


class ErrorResponse(BaseModel):
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    errors: Optional[List[Error]] = None


class Event(BaseModel):
    accountId: int = Field(..., description='Unique identifier of the account')
    answerTime: Optional[date] = Field(None, description='Time to answer the event')
    callerId: Optional[str] = Field(None, description='Remote caller ID')
    direction: Direction = Field(..., description='Direction of the event')
    duration: Optional[int] = Field(
        None, description='Duration of the call in milliseconds'
    )
    endTime: Optional[date] = Field(None, description='End time of the event')
    externalId: Optional[str] = Field(
        None, description='External identifier of the event'
    )
    id: int = Field(..., description='Unique identifier of the event')
    phoneNumber: str = Field(..., description='Unique identifier of the account')
    smsData: Optional[str] = None
    startTime: date = Field(..., description='Start time of the event')
    state: State = Field(..., description='Status of the event')
    type: Type = Field(..., description='Record type')
    uciId: int = Field(..., description='Unique identifier of communications provider')
    userId: int = Field(..., description='Unique identifier of the user')


class EventsCount(BaseModel):
    count: Optional[int] = Field(None, description='Number of events found')


class Role(BaseModel):
    code: Optional[str] = Field(None, description='Code for the role', examples=['AU'])
    name: Optional[str] = Field(
        None, description='Name for the role', examples=['Account User']
    )


class Uci1(BaseModel):
    health: Optional[Health] = None
    id: Optional[int] = None
    type: Optional[str] = 'USER_UCI'
    ucpLabel: Optional[str] = None


class User(BaseModel):
    accountId: Optional[int] = Field(
        None, description="Unique identifier of the user's account", examples=[257073]
    )
    acountLabel: Optional[str] = Field(
        None, description="The name of the user's account", examples=['Vonage']
    )
    contactNumber: Optional[str] = Field(
        None, description='Contact number of the user', examples=[14155550100]
    )
    emailAddress: Optional[str] = Field(
        None,
        description='Email address of the user',
        examples=['john.smith@example.com'],
    )
    firstName: Optional[str] = Field(
        None, description='First name of the user', examples=['Robert']
    )
    id: Optional[int] = Field(
        None, description='Unique identifier of the user', examples=[522078]
    )
    lastName: Optional[str] = Field(
        None, description='Last name of the user', examples=['Smith']
    )
    roles: Optional[List[Role]] = None
    status: Optional[Status] = Field(
        None, description='Status of the user', examples=['ACTIVE']
    )
    ucis: Optional[List[Uci1]] = None


class Event1(Enum):
    CALL = 'CALL'


class MetadataPolicy(Enum):
    NONE = 'NONE'
    HEADER = 'HEADER'
    BODY = 'BODY'


class SigningAlgo(Enum):
    HMAC_SHA256 = 'HMAC_SHA256'
    NONE = 'NONE'


class Statistics(BaseModel):
    failed: Optional[bool] = Field(
        None, description='Current delivery status', examples=[False]
    )
    totalAttempts: Optional[int] = Field(
        None, description='Total delivery attempts', examples=[10]
    )
    totalFailures: Optional[int] = Field(
        None, description='Total failed deliveries', examples=[10]
    )
    totalSuccesses: Optional[int] = Field(
        None, description='Total successful deliveries', examples=[10]
    )


class Status2(Enum):
    ACTIVE = 'ACTIVE'
    PAUSED = 'PAUSED'


class Webhook(BaseModel):
    accountId: Optional[str] = Field(
        None, description='Unique identifier of the account', examples=[257073]
    )
    createdAt: Optional[str] = Field(
        None,
        description='Created time for the webhook',
        examples=['2019-01-01T00:00:00.000Z'],
    )
    events: Optional[List[Event1]] = Field(
        None, description='Subscribed events for the webhook', examples=[['CALL']]
    )
    expireAt: Optional[str] = Field(
        None,
        description='Expiration time for the webhook',
        examples=['2019-01-01T00:00:00.000Z'],
    )
    id: Optional[str] = Field(
        None, description='Unique identifier for the webhook', examples=[184094]
    )
    metadataPolicy: Optional[MetadataPolicy] = Field(
        None, description='Metadata policy for the webhook', examples=['NONE']
    )
    purgeAt: Optional[str] = Field(
        None,
        description='Scheduled purge time for the webhook',
        examples=['2019-01-01T00:00:00.000Z'],
    )
    renewedAt: Optional[str] = Field(
        None,
        description='Last renewed time for the webhook',
        examples=['2019-01-01T00:00:00.000Z'],
    )
    signingAlgo: Optional[SigningAlgo] = Field(
        None, description='Signing algorithm for the webhook', examples=['HMAC_SHA256']
    )
    signingKey: Optional[str] = Field(None, description='Signing key for the webhook')
    statistics: Optional[Statistics] = None
    status: Optional[Status2] = Field(
        None, description='Status for the webhook', examples=['ACTIVE']
    )
    url: Optional[str] = Field(
        None,
        description='Destination URL for events',
        examples=['https://www.example.com'],
    )
    userId: Optional[str] = Field(
        None, description='Unique identifier of the user', examples=[522078]
    )


class SigningAlgo1(Enum):
    HMAC_SHA256 = 'HMAC_SHA256'


class WebhookCreate(BaseModel):
    events: Optional[List[Event1]] = Field(
        None, description='Events to subscribe to the webhook', examples=[['CALL']]
    )
    metadataPolicy: Optional[MetadataPolicy] = Field(
        None, description='Metadata policy for the webhook', examples=['NONE']
    )
    signingAlgo: Optional[SigningAlgo1] = Field(
        None, description='Signing algorithm for the webhook', examples=['HMAC_SHA256']
    )
    signingKey: Optional[str] = Field(None, description='Signing key for the webhook')
    url: Optional[str] = Field(
        None,
        description='Destination URL for events',
        examples=['https://www.example.com'],
    )


class States(Enum):
    INITIALIZING = 'INITIALIZING'
    RINGING = 'RINGING'
    ACTIVE = 'ACTIVE'
    HELD = 'HELD'
    REMOTE_HELD = 'REMOTE_HELD'


class Order(Enum):
    DESC = 'DESC'
    ASC = 'ASC'


class SelfCallsGetResponse(RootModel[List[Call]]):
    root: List[Call]


class SelfCallsPostResponse(RootModel[List[Call]]):
    root: List[Call]


class SelfCallsIdDeleteResponse(RootModel[List[Call]]):
    root: List[Call]


class SelfCallsIdGetResponse(RootModel[List[Call]]):
    root: List[Call]


class Types(Enum):
    CALL = 'CALL'


class States4(Enum):
    INITIALIZING = 'INITIALIZING'
    RINGING = 'RINGING'
    ACTIVE = 'ACTIVE'
    HELD = 'HELD'
    REMOTE_HELD = 'REMOTE_HELD'
    DETACHED = 'DETACHED'
    REJECTED = 'REJECTED'
    CANCELLED = 'CANCELLED'
    ANSWERED = 'ANSWERED'
    MISSED = 'MISSED'


class SelfEventsGetResponse(RootModel[List[Event]]):
    root: List[Event]


class States6(Enum):
    INITIALIZING = 'INITIALIZING'
    RINGING = 'RINGING'
    ACTIVE = 'ACTIVE'
    HELD = 'HELD'
    REMOTE_HELD = 'REMOTE_HELD'


class SelfEventsIdGetResponse(RootModel[List[Event]]):
    root: List[Event]


class SelfWebhooksGetResponse(RootModel[List[Webhook]]):
    root: List[Webhook]
